version: '3.8'

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.rule=Host(`${ADGUARD_HOST}`)"
      - "traefik.http.routers.adguardhome.entrypoints=websecure"
      - "traefik.http.routers.adguardhome.tls.certresolver=letsencrypt"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"

networks:
  frontend:
    external: true

