networks:
  frontend:
    external: true
services:
  wireguard:
    environment:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi)
      - LANG=fr
      - WG_HOST=${TRAEFIK_HOST}

      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_DNS=${PUBLIC_IP}
      - WG_ALLOWED_IPS=10.8.0.1/32
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)

    image: ghcr.io/wg-easy/wg-easy:14
    container_name: wireguard
    volumes:
      - ./wireguard/config:/etc/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wgeasy.rule=Host(`${WIREGUARD_HOST}`)"
      - "traefik.http.routers.wgeasy.entrypoints=websecure"
      - "traefik.http.routers.wgeasy.tls.certresolver=letsencrypt"
      - "traefik.http.services.wgeasy.loadbalancer.server.port=51821"
      - "traefik.http.routers.wgeasy.middlewares=auth@docker"

